language: generic
sudo: required
services: 
  - docker


before_install: 
  - docker build -t kajov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kajov/docker-react npm run test
